import "./globals.css";

export const metadata = {
  title: "Swensen's",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body>
        <header
          data-v-1def8f76
          data-v-6bbac5d6
          className="site-header ant-layout-header"
          id="header"
        >
          {/* <div data-v-1def8f76 className="header-left">
            <ul
              data-v-1def8f76
              role="menu"
              className="header-user-menu ant-menu ant-menu-horizontal ant-menu-root ant-menu-light"
            >
              <li
                role="menuitem"
                className="ant-menu-submenu ant-menu-submenu-horizontal ant-menu-overflowed-submenu"
                // style={display: none}
              >
                <div aria-haspopup="true" className="ant-menu-submit-title">
                  <span></span>
                </div>
              </li>
            </ul>
          </div>
          <div data-v-1def8f76 className="logo">
            <a
              data-v-1def8f76
              href="/en"
              aria-current="page"
              className="nuxt-link-exact-active nuxt-link=active"
            >
              <svg
                data-v-1def8f76
                width={103}
                height={26}
                viewBox="0 0 103 26"
                fill="none"
                xmlns="http://www.w3.org/2000/svg"
                className="swensens-logo"
              ></svg>
            </a>
          </div> */}
          <div
            data-v-1def8f76
            className="header-right ant-space-horizontal ant-space-align-center"
          >
            <div
              data-v-1def8f76
              className="ant-space-item"
              style={{ marginRight: "0px" }}
            >
              <div data-v-1def8f76 className="header-actions">
                <div
                  data-v-1def8f76
                  className="action-list ant-space ant-space-horizontal ant-space-align-center"
                >
                  <div
                    data-v-1def8f76
                    className="ant-space-item"
                    style={{ marginRight: "24px" }}
                  >
                    <a
                      data-v-1def8f76
                      href="/en/register"
                      className="header-button ant-btn"
                    >
                      <span>Register</span>
                    </a>
                  </div>
                  <div
                    data-v-1def8f76
                    className="ant-space-item"
                    style={{ marginRight: "24px" }}
                  >
                    <a
                      data-v-1def8f76
                      href="/en/login"
                      className="header-button ant-btn ant-btn-primary"
                    >
                      <span>Login</span>
                    </a>
                  </div>
                  <div data-v-1def8f76 className="ant-space-item">
                    <ul
                      data-v-1def8f76
                      role="menu"
                      className="header-user-menu ant-menu ant-menu-horizontal ant-menu-root ant-menu-light"
                    >
                    </ul>
                  </div>
                </div>
              </div>
            </div>
          </div>
        </header>
        <section>{children}</section>
      </body>
    </html>
  );
}
